### ISSUE TITLE
Format all price figures client-side to display as currencies

### ISSUE THREAD

**Issue by RWTreichel** [FlipSideHR/FlyptoX#184]

**Comment by RWTreichel** [comment]
Mostly done, just need to handle the account page's data table.

**Comment by mnaamani** [comment]
@RWTreichel BTC should not be rounded to two decimal places on front end

**Comment by RWTreichel** [comment]
It's not currently, at least I don't think...did you see that somewhere? By price I meant USD figures.

**Comment by mnaamani** [comment]
in the order entry where it show the BTC balance

![screen shot 2015-07-30 at 6 02 22 pm](https://cloud.githubusercontent.com/assets/1621012/8998661/3c7c61e2-36e5-11e5-99d0-69b02657fe59.png)
