### ISSUE TITLE
Create a working order book using coinbase data

### ISSUE THREAD

**Issue by recursion** [FlipSideHR/FlyptoX#58]
As an end user I want to see a live order book of current bids and offers.

Create an order book module in our angular skeleton that displays orders using the coinbase api.

**Comment by mnaamani** [comment]
I guess we can use our own api now :)

**Comment by RWTreichel** [comment]
"Using coinbase data" replace that with "using our orders API." Same idea though: we need a display very similar to what Simon had demo'ed a little while back that shows the order book in the correct order.
