### ISSUE TITLE
Create angular services

### ISSUE THREAD

**Issue by recursion** [FlipSideHR/FlyptoX#7]
As a front end developer I want angular services that I can consume for building out ux/ui. 

- These can just emit mock data for now but the data I get from these services should  match the actual data structures we will be using whenever possible.
- If someone was so inclined this would be a great use case for the angular service mocks that spidy showed us.
- The real things should be built to consume  our v0.0.1 api endpoints.

**Comment by RWTreichel** [comment]
This is a general one, but I'll be tackling it for now. AS things get more detailed we can break it down into smaller issues.
